version: '3.7'
services:

  elasticsearch:
    container_name: "elasticsearch"
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      xpack.monitoring.enabled: "true"
    # volumes:
    #  - ./esdata:/usr/share/elasticsearch/data
      
  kibana:
    container_name: "kibana"
    image: docker.elastic.co/kibana/kibana:7.15.1
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch

  redis:
    container_name: "redis"
    image: redis:3.0.1
    ports:
      - "6379:6379"

volumes:
  esdata:
    driver: local